name: CI

on:
  deployment:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Try sync
        run: |
          git clone https://${{ secrets.PUSH_TOKEN }}@github.com/iamtakingiteasy/se-torchapi-ds-docker.git
          cd se-torchapi-ds-docker
          ./sync.sh
